spring.application.name=webbeat

spring.data.mongodb.host=${SPRING_MONGO_HOST}
spring.data.mongodb.port=${SPRING_MONGO_PORT}

spring.data.mongodb.database=${MONGO_DB_NAME}
spring.data.mongodb.username=${SPRING_MONGO_USER}
spring.data.mongodb.password=${SPRING_MONGO_PASS}
spring.data.mongodb.authentication-database=${SPRING_MONGO_AUTH_DB}

logging.level.org.springframework.data.mongodb.core=DEBUG